services:
  postgresdb:
    container_name: postgresdb
    image: postgres:16.0
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:${PGDB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - sae

  web:
    container_name: web
    build: .
    ports:
      - ${PORT_WEB}:80
    volumes:
      - ../html:/var/www/html
    environment:
      VIRTUAL_HOST: localhost
    networks:
      - sae
    depends_on:
      - postgresdb

networks:
  sae:
